server:
  port: 80
  servlet:
    context-path: /
    session:
      timeout: 60m
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/be?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: P@ssw0rd.123
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
  jackson:
    time-zone: GMT+8
  aop:
    proxy-target-class: true
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,file:${resource.dir}
  mvc:
    static-path-pattern: /**
    favicon:
      enabled: false
  servlet:
    multipart:
      enabled: true
      #max-file-size: 50
      #max-request-size: 50
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    encoding: UTF-8
    enabled: true
    suffix: .html
    mode: HTML5
logging:
  path: ../be-logs
resource:
  dir: resources/